export const PLATFORM_META = {
  tinder: { name: 'Tinder', color: '#ff5a5f', short: 'TN' },
  bumble: { name: 'Bumble', color: '#f4a328', short: 'BM' },
  hinge: { name: 'Hinge', color: '#4b4b4b', short: 'HG' },
  instagram: { name: 'Instagram', color: '#d6336c', short: 'IG' },
  facebook: { name: 'Facebook', color: '#1877f2', short: 'FB' },
  linkedin: { name: 'LinkedIn', color: '#0a66c2', short: 'LI' },
  x: { name: 'X', color: '#1a1a1a', short: 'X' },
}

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'tinder', label: 'Tinder' },
  { id: 'bumble', label: 'Bumble' },
  { id: 'hinge', label: 'Hinge' },
  { id: 'instagram', label: 'Instagram' },
  { id: 'facebook', label: 'Facebook' },
  { id: 'linkedin', label: 'LinkedIn' },
]

export const initialAccounts = [
  {
    id: 'a1',
    platform: 'tinder',
    title: 'Tinder Gold | 1,200+ Matches',
    subtitle: 'Active boost · Passport · 5+ verified photos',
    priceHour: 4,
    priceDay: 28,
    rating: 4.9,
    reviews: 326,
    rentCount: 1284,
    tier: 'S',
    tags: ['Tinder Gold', '1,200+ matches', 'Boost ready'],
    games: [],
    image: '/assets/logos/tinder.svg',
    owner: 'My account',
    verified: true,
    stock: 3,
    deposit: 50,
    insured: true,
    status: 'online',
    featured: true,
    badge: 'Hot',
    description:
      'A polished Tinder Gold profile with a strong opening line, verified photos, and consistent match history. Ideal for testing openers, understanding swipe behavior, or running social experiments.',
    features: ['Instant login', 'Boost enabled', 'No device lock'],
    specs: { age: '26', location: 'New York', matches: '1,200+', boosts: 3 },
  },
  {
    id: 'a2',
    platform: 'bumble',
    title: 'Bumble Spotlight Pro',
    subtitle: '900+ matches · Hype mode · Verified profile',
    priceHour: 6,
    priceDay: 45,
    rating: 4.8,
    reviews: 214,
    rentCount: 862,
    tier: 'A',
    tags: ['Bumble Spotlight', '900+ matches', 'Verified'],
    games: ['Bumble', 'Dating'],
    image: '/assets/logos/bumble.svg',
    owner: 'Hype Vault',
    verified: true,
    stock: 2,
    deposit: 80,
    insured: true,
    status: 'online',
    featured: false,
    badge: 'Featured',
    description:
      'A proven Bumble profile with Spotlight credits and Hype mode ready. Great for testing conversation scripts, opening lines, and profile optimization without burning your own account.',
    features: ['Spotlight ready', 'Fast delivery', 'Support included'],
    specs: { location: 'Los Angeles', matches: '900+', photos: 6, spotlight: 2 },
  },
  {
    id: 'a3',
    platform: 'hinge',
    title: 'Hinge Ready & Proven',
    subtitle: '1,000+ likes · 60+ conversations · Prompts tuned',
    priceHour: 5,
    priceDay: 38,
    rating: 4.7,
    reviews: 158,
    rentCount: 641,
    tier: 'A',
    tags: ['Hinge', '1,000+ likes', 'High response'],
    games: ['Hinge'],
    image: '/assets/logos/hinge.svg',
    owner: 'My account',
    verified: true,
    stock: 1,
    deposit: 60,
    insured: true,
    status: 'risk',
    featured: false,
    badge: 'Verify',
    description:
      'A tuned Hinge profile with strong prompts and a fast response history. Perfect for studying conversation flow, testing messages, or comparing profile styles.',
    features: ['Instant login', 'Prompts tuned', 'Renewable'],
    specs: { location: 'Austin', likes: '1,000+', replies: '60+', photos: 6 },
  },
  {
    id: 'a4',
    platform: 'instagram',
    title: 'IG Travel Creator · 48K',
    subtitle: '48.2K followers · Story ready · Reels history',
    priceHour: 8,
    priceDay: 58,
    rating: 4.8,
    reviews: 489,
    rentCount: 2260,
    tier: 'S',
    tags: ['48K followers', 'Travel', 'Reels'],
    games: ['Instagram', 'Travel'],
    image: '/assets/logos/instagram.svg',
    owner: 'My account',
    verified: true,
    stock: 8,
    deposit: 100,
    insured: true,
    status: 'online',
    featured: true,
    badge: 'Hot rent',
    description:
      'Travel-focused Instagram creator account with 48K real followers and an active story presence. Suitable for brand research, content testing, and audience insights.',
    features: ['48K real followers', 'DM active', 'Story templates'],
    specs: { followers: '48.2K', niche: 'Travel', posts: 214, engagement: '6.8%' },
  },
  {
    id: 'a5',
    platform: 'instagram',
    title: 'IG Fashion Feed · 86K',
    subtitle: 'Fashion niche · High engagement · Brand-safe',
    priceHour: 9,
    priceDay: 68,
    rating: 4.9,
    reviews: 902,
    rentCount: 4180,
    tier: 'S',
    tags: ['86K followers', 'Fashion', 'High engagement'],
    games: ['Instagram', 'Fashion'],
    image: '/assets/logos/instagram.svg',
    owner: 'Social Stock',
    verified: true,
    stock: 3,
    deposit: 120,
    insured: true,
    status: 'online',
    featured: false,
    badge: 'Strict',
    description:
      'Fashion-focused Instagram account with 86K followers and strong post engagement. Great for analyzing feed strategies, collaborations, and creator workflows.',
    features: ['86K real followers', 'Brand-safe', 'Reels ready'],
    specs: { followers: '86K', niche: 'Fashion', posts: 340, engagement: '7.5%' },
  },
  {
    id: 'a6',
    platform: 'facebook',
    title: 'FB Dating Social Hub',
    subtitle: 'Verified profile · Marketplace access · Clean history',
    priceHour: 3,
    priceDay: 22,
    rating: 4.6,
    reviews: 73,
    rentCount: 190,
    tier: 'A',
    tags: ['Facebook', 'Dating', 'Marketplace'],
    games: ['Facebook', 'Dating'],
    image: '/assets/logos/facebook.svg',
    owner: 'Social Stock',
    verified: true,
    stock: 2,
    deposit: 40,
    insured: true,
    status: 'online',
    featured: false,
    badge: '',
    description:
      'A clean, verified Facebook account with Dating enabled and Marketplace access. Useful for social research, group testing, and community management practice.',
    features: ['Facebook Dating', 'Marketplace ready', 'Stable login'],
    specs: { region: 'US', age: 28, dating: true, groups: 4 },
  },
  {
    id: 'a7',
    platform: 'linkedin',
    title: 'LinkedIn Recruiter Pro',
    subtitle: '12K connections · Recruiter access · Clean history',
    priceHour: 7,
    priceDay: 52,
    rating: 4.7,
    reviews: 265,
    rentCount: 1380,
    tier: 'A',
    tags: ['LinkedIn', '12K connections', 'Recruiter'],
    games: ['LinkedIn', 'Networking'],
    image: '/assets/logos/linkedin.svg',
    owner: 'My account',
    verified: true,
    stock: 1,
    deposit: 120,
    insured: true,
    status: 'online',
    featured: false,
    badge: '',
    description:
      'Professional LinkedIn account with 12K connections and Recruiter access. Great for outreach testing, profile benchmarking, and content tone research.',
    features: ['Recruiter license', '12K connections', 'Premium inbox'],
    specs: { connections: '12K', premium: 'Recruiter', location: 'San Francisco', profile: 'Completed' },
  },
  {
    id: 'a8',
    platform: 'x',
    title: 'X Creator Network',
    subtitle: '35K followers · Engagement ready · No strikes',
    priceHour: 4,
    priceDay: 30,
    rating: 4.9,
    reviews: 188,
    rentCount: 756,
    tier: 'S',
    tags: ['X', '35K followers', 'Creator'],
    games: ['X', 'Social'],
    image: '/assets/logos/x.svg',
    owner: 'My account',
    verified: true,
    stock: 2,
    deposit: 90,
    insured: true,
    status: 'online',
    featured: true,
    badge: 'New',
    description:
      'Active X creator account with 35K followers and a clean history. Ideal for testing engagement tactics, monitoring feeds, and understanding platform dynamics.',
    features: ['35K followers', 'Fast DM', 'Clean history'],
    specs: { followers: '35K', verified: true, accountAge: '4y', replies: 'High' },
  },
  {
    id: 'a9',
    platform: 'tinder',
    title: 'Tinder Passport Explorer',
    subtitle: 'Worldwide passport · Active daily · Male profile',
    priceHour: 3,
    priceDay: 24,
    rating: 4.7,
    reviews: 96,
    rentCount: 430,
    tier: 'B',
    tags: ['Passport', 'Active', 'Openers'],
    games: ['Tinder', 'Dating'],
    image: '/assets/logos/tinder.svg',
    owner: 'Hype Vault',
    verified: true,
    stock: 5,
    deposit: 30,
    insured: true,
    status: 'online',
    featured: false,
    badge: '',
    description:
      'Daily active Tinder profile with worldwide Passport access. Great for location testing, opener practice, and swipe-pattern research.',
    features: ['Passport mode', 'Active account', 'Openers included'],
    specs: { location: 'London', age: 30, passport: 'Worldwide', photos: 5 },
  },
  {
    id: 'a10',
    platform: 'instagram',
    title: 'IG Lifestyle Vault · 120K',
    subtitle: 'Lifestyle niche · Reels heavy · DM friendly',
    priceHour: 10,
    priceDay: 78,
    rating: 4.8,
    reviews: 640,
    rentCount: 3100,
    tier: 'S',
    tags: ['120K followers', 'Lifestyle', 'Reels'],
    games: ['Instagram', 'Lifestyle'],
    image: '/assets/logos/instagram.svg',
    owner: 'Social Stock',
    verified: true,
    stock: 3,
    deposit: 150,
    insured: true,
    status: 'online',
    featured: false,
    badge: 'Strict',
    description:
      'Lifestyle creator account with 120K followers and a Reels-heavy feed. Suitable for content calendars, engagement studies, and influencer workflow demos.',
    features: ['120K followers', 'Reels templates', 'DM automation'],
    specs: { followers: '120K', niche: 'Lifestyle', reels: 90, engagement: '7.2%' },
  },
]

export const initialOrders = [
  {
    id: 'ord-1',
    accountId: 'a2',
    mode: 'hours',
    units: 3,
    amount: 18,
    status: 'active',
    started: 'Today 14:32',
    remainingMin: 68,
  },
  {
    id: 'ord-2',
    accountId: 'a7',
    mode: 'days',
    units: 2,
    amount: 104,
    status: 'scheduled',
    started: 'Tomorrow 10:00',
    remainingMin: 0,
  },
  {
    id: 'ord-3',
    accountId: 'a4',
    mode: 'hours',
    units: 2,
    amount: 16,
    status: 'ended',
    started: 'Today 09:10',
    remainingMin: 0,
  },
]

export const initialTasks = [
  {
    id: 't1',
    accountId: 'a1',
    kind: 'verify',
    title: 'Human verification',
    channel: 'Email code',
    reason: 'New sign-in detected',
    deadlineMin: 24,
    status: 'pending',
    steps: [
      'Platform emailed a 6-digit code',
      'Enter the code and confirm this sign-in',
      'Account goes live again after verification',
    ],
  },
  {
    id: 't2',
    accountId: 'a3',
    kind: 'ban_risk',
    title: 'Ban risk review',
    channel: 'Security center',
    reason: 'Multiple sessions triggered risk control',
    deadlineMin: 58,
    status: 'pending',
    steps: [
      'Confirm active devices in platform security center',
      'Close unknown sessions and enable login protection',
      'Confirm account is safe to relist',
    ],
  },
]

export const initialNotifications = [
  {
    id: 'n1',
    type: 'verify',
    severity: 'urgent',
    title: 'Tinder account needs human verification',
    message:
      '"Tinder Gold | 1,200+ Matches" triggered a sign-in review. Complete verification as soon as possible.',
    time: '3 min ago',
    read: false,
    accountId: 'a1',
    action: 'verify',
  },
  {
    id: 'n2',
    type: 'ban_risk',
    severity: 'high',
    title: 'Hinge account flagged for shared use',
    message:
      '"Hinge Ready & Proven" was paused after multiple simultaneous logins. Confirm account safety to resume renting.',
    time: '16 min ago',
    read: false,
    accountId: 'a3',
    action: 'verify',
  },
  {
    id: 'n3',
    type: 'order',
    severity: 'normal',
    title: 'New order paid',
    message:
      'Renter "NightOwl" paid $18 for 3 hours on Bumble Spotlight Pro. Credentials were issued automatically.',
    time: '42 min ago',
    read: true,
    accountId: 'a2',
    action: 'order',
  },
  {
    id: 'n4',
    type: 'system',
    severity: 'normal',
    title: 'Platform protection active',
    message: 'Account insurance is active. Bans and disputes are covered by the platform guarantee.',
    time: 'Yesterday',
    read: true,
    action: 'none',
  },
]

export const fallbackCover = {
  tinder: '/assets/logos/tinder.svg',
  bumble: '/assets/logos/bumble.svg',
  hinge: '/assets/logos/hinge.svg',
  instagram: '/assets/logos/instagram.svg',
  facebook: '/assets/logos/facebook.svg',
  linkedin: '/assets/logos/linkedin.svg',
  x: '/assets/logos/x.svg',
}

export function makeId(prefix) {
  if (globalThis.crypto && typeof globalThis.crypto.randomUUID === 'function') {
    return `${prefix}-${globalThis.crypto.randomUUID().slice(0, 8)}`
  }
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`
}

export function formatPrice(value) {
  return Number.isInteger(value) ? `$${value}` : `$${value.toFixed(1)}`
}
